### ISSUE TITLE
Правки на главной странице

### ISSUE THREAD

**Issue by vladyslav2** [webdeveloppro/vichara#21]
- [x] @prottones забыли иконки apple / google play с ссылками на скачать приложение 
- [x] переключатель языка (en/ru/uk/es)

**Comment by prottones** [comment]
@vladyslav2 
https://marvelapp.com/a244d4e/screen/52179961

**Comment by prottones** [comment]
если все ок, отпиши — залью в Зеплин

**Comment by vladyslav2** [comment]
да супер
